submitit ERROR (2024-11-22 13:46:10,773) - Submitted job triggered an exception
Traceback (most recent call last):
  File "E:\anaconda\envs\wsissl\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\anaconda\envs\wsissl\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\anaconda\envs\wsissl\lib\site-packages\submitit\core\_submit.py", line 11, in <module>
    submitit_main()
  File "E:\anaconda\envs\wsissl\lib\site-packages\submitit\core\submission.py", line 76, in submitit_main
    process_job(args.folder)
  File "E:\anaconda\envs\wsissl\lib\site-packages\submitit\core\submission.py", line 69, in process_job
    raise error
  File "E:\anaconda\envs\wsissl\lib\site-packages\submitit\core\submission.py", line 54, in process_job
    env._handle_signals(paths, delayed)
  File "E:\anaconda\envs\wsissl\lib\site-packages\submitit\core\job_environment.py", line 153, in _handle_signals
    signal.signal(self._usr_sig(), handler.checkpoint_and_try_requeue)
  File "E:\anaconda\envs\wsissl\lib\site-packages\submitit\core\job_environment.py", line 141, in _usr_sig
    raise RuntimeError(
RuntimeError: Unknown signal SIGUSR2, you may need to unset or update env var SUBMITIT_PREEMPT_SIGNAL (Eg: USR2)
